spring:
  application.name: amigosecreto

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl: auto